### ISSUE TITLE
💡 Add color input for speaker name talk template

### ISSUE THREAD

**Issue by geromegrignon** [lyonjs/shortvid.io#1140]
# Feature Request 👨🏼‍💻

Add a color input to change the text color of the speaker name in the Talk template

## Use Case ✍🏼

By design it currently use the LyonJS color, the goal is to be able to use other event design.

## Possible Solution 💡

I'd like to contribute by adding the input

**Comment by CruuzAzul** [comment]
I'll take a look at it 😎

**Comment by geromegrignon** [comment]
@CruuzAzul  There is 'speakerNameColor' to be renamed but i made a PR with related code on a fork meanwhile to test it for our meetup: https://github.com/angular-devs-france/shortvid.io/commit/285de65e67bf660192f7cc16ee80ccfdbbe841c5

**Comment by CruuzAzul** [comment]
@geromegrignon Oh great, I didn't know you were using it, it's really cool! 🤩 I'll make the change. FYI, we'll soon be looking to release a new version of shortvid.io, from now on Remotion will allow you to have a form directly in the studio, so the application we have in Next will soon disappear to be replaced by the studio that we're going to improve!

**Comment by geromegrignon** [comment]
Not yet, we plan to use it starting in September for social media.
Great news for the release!
