### ISSUE TITLE
🐞 Fix useLottie to avoid freeze

### ISSUE THREAD

**Issue by CruuzAzul** [lyonjs/shortvid.io#200]
# Describe the bug 🐛

From time to time on the application when we have a player that displays lotties we have the application freezing. The problem comes from the display of our lotties and maybe more precisely from the hook. We need to find out where this is coming from and fix the problem

## Expected behavior 🦾

The application should not freeze 🤷🏼‍♂️

**Comment by Boyadjie** [comment]
Maybe the app freeze because the request is sent too many times ? Every time that a component that contain a lottie is mounted, the hook is called and so an api call is made, so maybe that what make the app freeze ?
