### ISSUE TITLE
💡 Create `fontContext` to generalise the default font

### ISSUE THREAD

**Issue by CruuzAzul** [lyonjs/shortvid.io#206]
# Feature Request 👨🏼‍💻

In the app as in the remotion preview, we need to have a default font. Today, its set every time we need a font.

## Use Case ✍🏼

It will allow us to use the same default font everywhere, especially in the remotion preview, when you just want to see an atom, it's better with a good font.

## Possible Solution 💡

Create a `fontContext` with by default the font 'noto-sans' and use it for the remotion preview and the app

**Comment by Boyadjie** [comment]
With the UX/UI refacto, if we want the font to be persistent even when moving to another template, couldn't it be better for the font-picker input to be externalise ? We could put it under the list of templates/showcases maybe ?
