### ISSUE TITLE
💡 Create `Details` molecule for talk

### ISSUE THREAD

**Issue by CruuzAzul** [lyonjs/shortvid.io#214]
# Feature Request 👨🏼‍💻

We want to create a new `Details` molecule to be used in our compositions

## Use Case ✍🏼

In many compositions a `Details` component is used which has been duplicated each time for some differences. We want to have a single component where we can override the style for the animations and the few differences.

## Possible Solution 💡

Using the atom created with #215 we can juste make a component we can just make a component that displays three `IconCaption` for the date, time and location. These parameters will of course be optional 

ℹ️ Once this is done, update the different templates

**Comment by Boyadjie** [comment]
The composition iconWithCaption will contain an icon and a caption (text atom), doesn't that make it a molecule and Details an organism ?
