### ISSUE TITLE
💡 Implement React Testing Library

### ISSUE THREAD

**Issue by CruuzAzul** [lyonjs/shortvid.io#330]
# Feature Request 👨🏼‍💻

Implement React Testing Library for project testing 🧪

## Use Case ✍🏼

As developers, we want to ensure the stability and reliability of our project by implementing a robust testing framework. By introducing React Testing Library, we aim to facilitate the testing process and improve the overall quality of our codebase.

## Possible Solution 💡

1. Install React Testing Library as a project dependency.
2. Create separate folders for the tests.
3. Integrate testing into the project's development workflow.
4. List all current components that need to be tested (make US 🏷️)

**Comment by Boyadjie** [comment]
Components To Test :
/App
- Header
- Footer
- NavBar
- LayerByMode
- CopyUrlButton
- Code
- ActiveLink
- /utils
	- encodedObjectValues
	- formatUrlWithQuery
	- loadFont
- /hooks
	- useInputChange
	- useInputDateChange
	- useSelectedFont
- /forms
	- colorInput
	- FontPicker
	- input
	- inputDate
	- selectInput

/remotion
- /molecules
	- AvatarWithCaption
	- IconWithCaption
	- TalkDetails
