### ISSUE TITLE
💡 Test: ActiveLink component

### ISSUE THREAD

**Issue by Boyadjie** [lyonjs/shortvid.io#350]
# Feature Request 👨🏼‍💻

We want to test the components on the app

## Use Case ✍🏼

At any modification on the code we want to be sure that everything work fine.

## Possible Solution 💡

Create the test file and make the test using jest and react-testing-library

**Comment by pedenys** [comment]
Hi ! I will submit a PR this weekend for this test.

**Comment by CruuzAzul** [comment]
Thanks a lot ! 🫶🏼
