### ISSUE TITLE
🐞 Font Family not rendered 

### ISSUE THREAD

**Issue by Boyadjie** [lyonjs/shortvid.io#484]
# Describe the bug 🐛

When you render the Event video with a custom font, it take noto sans and don't render with the chosen font.

## Expected behavior 🦾

We want to render with the selected font

## Screenshots 📸

Should render with banger font
<img width="1100" alt="image" src="https://github.com/lyonjs/shortvid.io/assets/72607059/10f2b0a8-11de-4386-a6e5-f848373c0d57">

But don't
https://github.com/lyonjs/shortvid.io/assets/72607059/d54678ef-462d-4f61-a895-3ce9ffe4416f

**Comment by light-200** [comment]
Hey @Boyadjie I'd like to work on the issue, can you assign it to me?

**Comment by light-200** [comment]
hey @Boyadjie I've been trying to fix the bug but so far I haven't made much progress.
i already checked the **loadfont()** method and it while it does imports the selected font **before rendering** of the frames starts, it switches to **importing 'Noto Sans'** font **while rendering** the frames. 
I can't seem to figure out why it switches back to the default selected font.
It'll be great if you could guide me a bit on what can I do to fix the bug.

**Comment by CruuzAzul** [comment]
Hi @light-200! Sorry for taking so long to reply, but I think we're going to look at doing things differently for this issue, so we'll think about it. Thanks for trying to work on it! ❤️
