### ISSUE TITLE
🐞 Problem with the date in the generated video

### ISSUE THREAD

**Issue by jlandure** [lyonjs/shortvid.io#791]
# Describe the bug 🐛

I wanted to generate a video with the time 18h30
The JSON parameter is set at 17h30 

```
pnpm remotion render remotion/index.tsx TalkBranded out/TalkBranded.mp4 --props='{"backgroundColor":"#086fda","title":"CI/CD avec Dataflow dans Google Cloud","startingDate":"2024-02-01T17:30:00.000Z","location":"GDG Cloud Nantes & GDG Cloud Abidjan","logoUrl":"https://user-images.githubusercontent.com/72607059/233019842-047a34a4-77c1-4200-adc8-c70a6daf8f10.svg","speaker":{"pictureUrl":"https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2,f_auto,g_face,h_200,q_auto:good,w_200/v1/gcs/platform-data-goog/events/profile_photo_gde_well_sized.png","name":"Mazlum Tosun","company":null,"job":null}}'
```

The result is that the generated video says that the event is at 17h30 instead of 18h30 like I set in the browser

## Expected behavior 🦾

Get the time I've set in the generated video.

## Screenshots 📸

<img width="994" alt="image" src="https://github.com/lyonjs/shortvid.io/assets/525974/0180fff2-5e45-4a83-b5ff-46cbe952163f">

**Comment by Slashgear** [comment]
Nice catch !

**Comment by HugoGresse** [comment]
I think we have the same issue, even when providing the date `2024-01-01T13:10:00.000+01:00` the final date in the image is minus 1h
